### ISSUE TITLE
After killing the process, it becomes a zombie process

### ISSUE THREAD

**Issue by iamfengdy** [jina-ai/serve#6166]
1. nohup jina flow --uses flow.yml --name bf7e2d0198df3388a73525a3f3c7f87f --workspace bf7e2d0198df3388a73525a3f3c7f87f >bf7e2d0198df3388a73525a3f3c7f87f/jina.log 2>&1 &
2. ps aux|grep 'jina flow '|grep 'name bf7e2d0198df3388a73525a3f3c7f87f' |grep -v grep |awk '{print $2}'| xargs echo
outputs are: 1719527 1719529 1721841
3. kill -9 1719527 1719529 1721841
4. processes(1719527 1719529 1721841) becomes zombie process

**Comment by JoanFM** [comment]
can u share the logs observed?

**Comment by iamfengdy** [comment]
INFO   executor/rep-0@49 start server bound to 0.0.0.0:54054 [04/29/24 09:34:55]
────────────────────────── 🎉 Flow is ready to serve! ──────────────────────────
╭────────────── 🔗 Endpoint ───────────────╮
│  ⛓      Protocol                   HTTP  │
│  🏠        Local           0.0.0.0:5000  │
│  🔒      Private      192.168.2.89:5000  │
│  🌍       Public     xxx.xxx.xxx.xxx:5000  │
╰──────────────────────────────────────────╯
╭─────────── 💎 HTTP extension ────────────╮
│  💬     Swagger UI    0.0.0.0:5000/docs  │
│  📚          Redoc   0.0.0.0:5000/redoc  │
╰──────────────────────────────────────────╯
Do you love open source? Help us improve Jina in just 1 minute and 30 seconds by
taking our survey:
https://10sw1tcpld4.typeform.com/jinasurveyfeb23?utm_source=jina (Set
environment variable JINA_HIDE_SURVEY=1 to hide this message.)

**Comment by iamfengdy** [comment]
by the way. i run jina in docker container  and the  os  version is "Linux  4.4.0-210-generic #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021 x86_64 GNU/Linux"

**Comment by iamfengdy** [comment]
killing process by subprocess.run("kill -9 ")  in python will occur zombie process;
but by kill command in linux will not occur

**Comment by JoanFM** [comment]
can u pass the `JINA_LOG_LEVEL=DEBUG` environmenr variable to see more log information?

**Comment by JoanFM** [comment]
> killing process by subprocess.run("kill -9 ") in python will occur zombie process; but by kill command in linux will not occur

I think this may be the reason.

**Comment by iamfengdy** [comment]
> > killing process by subprocess.run("kill -9 ") in python will occur zombie process; but by kill command in linux will not occur
> 
> I think this may be the reason.

whether using python  or command , it will occur when running in a container, this may be the reason.

**Comment by scottt732** [comment]
If you're on an Apple Silicon mac, try setting `JINA_MP_START_METHOD=spawn`. `fork` was causing zombie processes/failing to process requests on my M1 macbook.

**Comment by iamfengdy** [comment]
OK，i was on ubuntu ，but i will have a try，thanks。

发自我的 ifeng6p
