### ISSUE TITLE
Jina AI install error on Ubuntu 22.04 and Python 3.12 system

### ISSUE THREAD

**Issue by teetangh** [jina-ai/serve#6186]
**Describe the bug**
The error pops up when i try to install the jina-ai python package on my Ubuntu machine.
Building GRPC wheel failure.
[jina install error.txt](https://github.com/user-attachments/files/16538089/jina.install.error.txt)

**Describe how you solve it**
Not Solved yet

---

**Environment**
Ubuntu 22.04 and Python 3.12

**Screenshots**
The Entire error log is in the above txt file

**Comment by JoanFM** [comment]
does it happen also with Python3.11

**Comment by teetangh** [comment]
Works on my mac with Python 3.11
ubtuntu 22.04 comes with Python 3.12. 
Request you to make a port for the 3.12

**Comment by JoanFM** [comment]
I will check in some time as I am away. In the meantime, I suggest that u can use a virtual environment with Python3.11

**Comment by teetangh** [comment]
@JoanFM Any update on this ?

**Comment by teetangh** [comment]
I tried it just now 
[jina-error-08-nov-2024.txt](https://github.com/user-attachments/files/17681839/jina-error-08-nov-2024.txt)

**Comment by JoanFM** [comment]
sorry, the release did not work. Will try to release soon and ask u again to try

**Comment by teetangh** [comment]
@JoanFM Thanks man.

**Comment by JoanFM** [comment]
@teetangh have u tried?

**Comment by lyksdu** [comment]
@JoanFM  恰巧看到这个issue，我在我的debian机器上试了一下，看起来jina-3.33.0版本的安装是顺利的。我的环境是debian trixie

**Comment by JoanFM** [comment]
@lyksdu thanks, so u confirm is solved?

**Comment by lyksdu** [comment]
I have no experience in using Jina. However, if the issue only refers to the installation process, I think this issue should have been resolved. @JoanFM

**Comment by JoanFM** [comment]
Thx!
